version: '3.4'

services:
  altencarstore.vehicleservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  altencarstore.driverservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  altencarstore.vehiclestateservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  altencarstore.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

